const res = {
    "notificationLastReadDate": null,
    "notifications": [
        {
            "id": "jXao5ZEBZQG_1GkRzh8W",
            "category": "JOBS",
            "subCategory": "CLIENT_OFFER_ACCEPTED",
            "subject": "Offer Accepted",
            "content": "Gary Pm has accepted offer at Dialyze Direct-Maryland RN ADON.",
            "clientContactId": 2399211,
            "candidateId": 20561591,
            "clientId": 830410,
            "pinToTop": false,
            "favourite": false,
            "organizationId": 149,
            "createdBy": 691421,
            "notificationRead": true,
            "candidateName": "Gary Pm",
            "clientName": "Dialyze Direct-Maryland",
            "entityId": null,
            "createdDate": "09-12-2024 09:55:30",
            "createdDateZoned": "2024-09-12T09:55:30Z",
            "modifiedBy": 691421,
            "modifiedDate": "09-12-2024 09:55:30",
            "professionId": null,
            "professionIds": null,
            "orderId": null,
            "specialtyId": null,
            "specialtyIds": null,
            "jobSubmittalId": 762876,
            "jobId": 14543812,
            "orderCandidateId": null,
            "displayOnExternalJobBoard": false,
            "shiftAccepted": false,
            "shiftDate": null,
            "jobEndDate": null,
            "offerAcceptedDate": "2024-09-12T09:55:26",
            "title": null,
            "candidateNotes": null,
            "clientNotes": null,
            "subscribedUserIds": null,
            "categoryName": null,
            "subCategoryName": null
        },
        {
            "id": "dnam5ZEBZQG_1GkRsB92",
            "category": "JOBS",
            "subCategory": "CLIENT_MOBILE_NEW_SUBMITTAL",
            "subject": "New Submittal",
            "content": "You have a new submittal for Dialyze Direct-Maryland RN - ADON",
            "clientContactId": 2399211,
            "candidateId": 20561591,
            "clientId": 830410,
            "pinToTop": false,
            "favourite": false,
            "organizationId": 149,
            "createdBy": 691421,
            "notificationRead": false,
            "candidateName": "Gary Pm",
            "clientName": "Dialyze Direct-Maryland",
            "entityId": null,
            "createdDate": "09-12-2024 09:53:12",
            "createdDateZoned": "2024-09-12T09:53:12Z",
            "modifiedBy": 691421,
            "modifiedDate": "09-12-2024 09:53:12",
            "professionId": null,
            "professionIds": null,
            "orderId": null,
            "specialtyId": null,
            "specialtyIds": null,
            "jobSubmittalId": 762876,
            "jobId": 14543812,
            "orderCandidateId": null,
            "displayOnExternalJobBoard": false,
            "shiftAccepted": false,
            "shiftDate": null,
            "jobEndDate": null,
            "offerAcceptedDate": "2024-09-12T09:55:26",
            "title": null,
            "candidateNotes": null,
            "clientNotes": null,
            "subscribedUserIds": null,
            "categoryName": null,
            "subCategoryName": null
        },
        {
            "id": "bnZY5ZEBZQG_1GkRhB6x",
            "category": "JOBS",
            "subCategory": "CLIENT_MOBILE_SUBMITTAL_WITHDRAWN",
            "subject": "Submittal Withdrawn",
            "content": "Gary Pm was withdrawn from Dialyze Direct-Maryland RN - ADON.",
            "clientContactId": 2399211,
            "candidateId": 20561591,
            "clientId": 830410,
            "pinToTop": false,
            "favourite": false,
            "organizationId": 149,
            "createdBy": 691421,
            "notificationRead": false,
            "candidateName": "Gary Pm",
            "clientName": "Dialyze Direct-Maryland",
            "entityId": null,
            "createdDate": "09-12-2024 08:27:49",
            "createdDateZoned": "2024-09-12T08:27:49Z",
            "modifiedBy": 691421,
            "modifiedDate": "09-12-2024 08:27:49",
            "professionId": null,
            "professionIds": null,
            "orderId": null,
            "specialtyId": null,
            "specialtyIds": null,
            "jobSubmittalId": 762065,
            "jobId": 14540974,
            "orderCandidateId": null,
            "displayOnExternalJobBoard": true,
            "shiftAccepted": false,
            "shiftDate": null,
            "jobEndDate": null,
            "offerAcceptedDate": null,
            "title": null,
            "candidateNotes": null,
            "clientNotes": null,
            "subscribedUserIds": null,
            "categoryName": null,
            "subCategoryName": null
        },
        {
            "id": "yXZ64pEBZQG_1GkRcRm6",
            "category": "JOBS",
            "subCategory": "CLIENT_OFFER_DECLINED",
            "subject": "Offer Declined",
            "content": "Bryson Jenkins has declined the offer at Dialyze Direct-Maryland RN ADON. Reason: test ",
            "clientContactId": 2399211,
            "candidateId": 20561551,
            "clientId": 830410,
            "pinToTop": false,
            "favourite": false,
            "organizationId": 149,
            "createdBy": 691392,
            "notificationRead": true,
            "candidateName": "Bryson Jenkins",
            "clientName": "Dialyze Direct-Maryland",
            "entityId": null,
            "createdDate": "09-11-2024 19:06:00",
            "createdDateZoned": "2024-09-11T19:06:00Z",
            "modifiedBy": 691392,
            "modifiedDate": "09-11-2024 19:06:00",
            "professionId": null,
            "professionIds": null,
            "orderId": null,
            "specialtyId": null,
            "specialtyIds": null,
            "jobSubmittalId": 762791,
            "jobId": 14543542,
            "orderCandidateId": null,
            "displayOnExternalJobBoard": true,
            "shiftAccepted": false,
            "shiftDate": null,
            "jobEndDate": "2024-10-19",
            "offerAcceptedDate": null,
            "title": null,
            "candidateNotes": null,
            "clientNotes": null,
            "subscribedUserIds": null,
            "categoryName": null,
            "subCategoryName": null
        },
        {
            "id": "_nYH4ZEBZQG_1GkRCAah",
            "category": "JOBS",
            "subCategory": "CLIENT_MOBILE_NEW_SUBMITTAL",
            "subject": "New Submittal",
            "content": "You have a new submittal for Dialyze Direct-Maryland Certified Medical Assistant - EKG Tech",
            "clientContactId": 2399211,
            "candidateId": 20561591,
            "clientId": 830410,
            "pinToTop": false,
            "favourite": false,
            "organizationId": 149,
            "createdBy": 691421,
            "notificationRead": false,
            "candidateName": "Gary Pm",
            "clientName": "Dialyze Direct-Maryland",
            "entityId": null,
            "createdDate": "09-11-2024 12:20:20",
            "createdDateZoned": "2024-09-11T12:20:20Z",
            "modifiedBy": 691421,
            "modifiedDate": "09-11-2024 12:20:20",
            "professionId": null,
            "professionIds": null,
            "orderId": null,
            "specialtyId": null,
            "specialtyIds": null,
            "jobSubmittalId": 762873,
            "jobId": 14543787,
            "orderCandidateId": null,
            "displayOnExternalJobBoard": true,
            "shiftAccepted": false,
            "shiftDate": null,
            "jobEndDate": "2024-12-21",
            "offerAcceptedDate": null,
            "title": null,
            "candidateNotes": null,
            "clientNotes": null,
            "subscribedUserIds": null,
            "categoryName": null,
            "subCategoryName": null
        },
        {
            "id": "3XYG4ZEBZQG_1GkRQwa0",
            "category": "JOBS",
            "subCategory": "CLIENT_MOBILE_NEW_SUBMITTAL",
            "subject": "New Submittal",
            "content": "You have a new submittal for Dialyze Direct-Maryland Certified Medical Assistant - EKG Tech",
            "clientContactId": 2399211,
            "candidateId": 20561591,
            "clientId": 830410,
            "pinToTop": false,
            "favourite": false,
            "organizationId": 149,
            "createdBy": 691421,
            "notificationRead": false,
            "candidateName": "Gary Pm",
            "clientName": "Dialyze Direct-Maryland",
            "entityId": null,
            "createdDate": "09-11-2024 12:19:29",
            "createdDateZoned": "2024-09-11T12:19:29Z",
            "modifiedBy": 691421,
            "modifiedDate": "09-11-2024 12:19:29",
            "professionId": null,
            "professionIds": null,
            "orderId": null,
            "specialtyId": null,
            "specialtyIds": null,
            "jobSubmittalId": 762873,
            "jobId": 14543787,
            "orderCandidateId": null,
            "displayOnExternalJobBoard": true,
            "shiftAccepted": false,
            "shiftDate": null,
            "jobEndDate": "2024-12-21",
            "offerAcceptedDate": null,
            "title": null,
            "candidateNotes": null,
            "clientNotes": null,
            "subscribedUserIds": null,
            "categoryName": null,
            "subCategoryName": null
        },
        {
            "id": "yHYE4ZEBZQG_1GkRfAZd",
            "category": "JOBS",
            "subCategory": "CLIENT_MOBILE_NEW_SUBMITTAL",
            "subject": "New Submittal",
            "content": "You have a new submittal for Dialyze Direct-Maryland Certified Medical Assistant - EKG Tech",
            "clientContactId": 2399211,
            "candidateId": 20561591,
            "clientId": 830410,
            "pinToTop": false,
            "favourite": false,
            "organizationId": 149,
            "createdBy": 691421,
            "notificationRead": false,
            "candidateName": "Gary Pm",
            "clientName": "Dialyze Direct-Maryland",
            "entityId": null,
            "createdDate": "09-11-2024 12:17:33",
            "createdDateZoned": "2024-09-11T12:17:33Z",
            "modifiedBy": 691421,
            "modifiedDate": "09-11-2024 12:17:33",
            "professionId": null,
            "professionIds": null,
            "orderId": null,
            "specialtyId": null,
            "specialtyIds": null,
            "jobSubmittalId": 762873,
            "jobId": 14543787,
            "orderCandidateId": null,
            "displayOnExternalJobBoard": true,
            "shiftAccepted": false,
            "shiftDate": null,
            "jobEndDate": "2024-12-21",
            "offerAcceptedDate": null,
            "title": null,
            "candidateNotes": null,
            "clientNotes": null,
            "subscribedUserIds": null,
            "categoryName": null,
            "subCategoryName": null
        },
        {
            "id": "Dnbu4JEBZQG_1GkRTwZy",
            "category": "JOBS",
            "subCategory": "CLIENT_MOBILE_NEW_SUBMITTAL",
            "subject": "New Submittal",
            "content": "You have a new submittal for Dialyze Direct-Maryland Certified Medical Assistant - EKG Tech",
            "clientContactId": 2399211,
            "candidateId": 20561591,
            "clientId": 830410,
            "pinToTop": false,
            "favourite": false,
            "organizationId": 149,
            "createdBy": 691421,
            "notificationRead": false,
            "candidateName": "Gary Pm",
            "clientName": "Dialyze Direct-Maryland",
            "entityId": null,
            "createdDate": "09-11-2024 11:53:19",
            "createdDateZoned": "2024-09-11T11:53:19Z",
            "modifiedBy": 691421,
            "modifiedDate": "09-11-2024 11:53:19",
            "professionId": null,
            "professionIds": null,
            "orderId": null,
            "specialtyId": null,
            "specialtyIds": null,
            "jobSubmittalId": 762873,
            "jobId": 14543787,
            "orderCandidateId": null,
            "displayOnExternalJobBoard": true,
            "shiftAccepted": false,
            "shiftDate": null,
            "jobEndDate": "2024-12-21",
            "offerAcceptedDate": null,
            "title": null,
            "candidateNotes": null,
            "clientNotes": null,
            "subscribedUserIds": null,
            "categoryName": null,
            "subCategoryName": null
        },
        {
            "id": "9Hbn4JEBZQG_1GkR_wVU",
            "category": "JOBS",
            "subCategory": "CLIENT_MOBILE_NEW_SUBMITTAL",
            "subject": "New Submittal",
            "content": "You have a new submittal for Dialyze Direct-Maryland Certified Medical Assistant - EKG Tech",
            "clientContactId": 2399211,
            "candidateId": 20561591,
            "clientId": 830410,
            "pinToTop": false,
            "favourite": false,
            "organizationId": 149,
            "createdBy": 691421,
            "notificationRead": false,
            "candidateName": "Gary Pm",
            "clientName": "Dialyze Direct-Maryland",
            "entityId": null,
            "createdDate": "09-11-2024 11:46:26",
            "createdDateZoned": "2024-09-11T11:46:26Z",
            "modifiedBy": 691421,
            "modifiedDate": "09-11-2024 11:46:26",
            "professionId": null,
            "professionIds": null,
            "orderId": null,
            "specialtyId": null,
            "specialtyIds": null,
            "jobSubmittalId": 762873,
            "jobId": 14543787,
            "orderCandidateId": null,
            "displayOnExternalJobBoard": true,
            "shiftAccepted": false,
            "shiftDate": null,
            "jobEndDate": "2024-12-21",
            "offerAcceptedDate": null,
            "title": null,
            "candidateNotes": null,
            "clientNotes": null,
            "subscribedUserIds": null,
            "categoryName": null,
            "subCategoryName": null
        },
        {
            "id": "1Hbi4JEBZQG_1GkREgX5",
            "category": "JOBS",
            "subCategory": "CLIENT_MOBILE_NEW_SUBMITTAL",
            "subject": "New Submittal",
            "content": "You have a new submittal for Dialyze Direct-Maryland Certified Medical Assistant - EKG Tech",
            "clientContactId": 2399211,
            "candidateId": 20561591,
            "clientId": 830410,
            "pinToTop": false,
            "favourite": false,
            "organizationId": 149,
            "createdBy": 691421,
            "notificationRead": false,
            "candidateName": "Gary Pm",
            "clientName": "Dialyze Direct-Maryland",
            "entityId": null,
            "createdDate": "09-11-2024 11:39:57",
            "createdDateZoned": "2024-09-11T11:39:57Z",
            "modifiedBy": 691421,
            "modifiedDate": "09-11-2024 11:39:57",
            "professionId": null,
            "professionIds": null,
            "orderId": null,
            "specialtyId": null,
            "specialtyIds": null,
            "jobSubmittalId": 762873,
            "jobId": 14543787,
            "orderCandidateId": null,
            "displayOnExternalJobBoard": true,
            "shiftAccepted": false,
            "shiftDate": null,
            "jobEndDate": "2024-12-21",
            "offerAcceptedDate": null,
            "title": null,
            "candidateNotes": null,
            "clientNotes": null,
            "subscribedUserIds": null,
            "categoryName": null,
            "subCategoryName": null
        },
        {
            "id": "mXbU4JEBZQG_1GkR9AXO",
            "category": "JOBS",
            "subCategory": "CLIENT_MOBILE_NEW_SUBMITTAL",
            "subject": "New Submittal",
            "content": "You have a new submittal for Dialyze Direct-Maryland Certified Medical Assistant - EKG Tech",
            "clientContactId": 2399211,
            "candidateId": 20561591,
            "clientId": 830410,
            "pinToTop": false,
            "favourite": false,
            "organizationId": 149,
            "createdBy": 691421,
            "notificationRead": false,
            "candidateName": "Gary Pm",
            "clientName": "Dialyze Direct-Maryland",
            "entityId": null,
            "createdDate": "09-11-2024 11:25:38",
            "createdDateZoned": "2024-09-11T11:25:38Z",
            "modifiedBy": 691421,
            "modifiedDate": "09-11-2024 11:25:38",
            "professionId": null,
            "professionIds": null,
            "orderId": null,
            "specialtyId": null,
            "specialtyIds": null,
            "jobSubmittalId": 762873,
            "jobId": 14543787,
            "orderCandidateId": null,
            "displayOnExternalJobBoard": true,
            "shiftAccepted": false,
            "shiftDate": null,
            "jobEndDate": "2024-12-21",
            "offerAcceptedDate": null,
            "title": null,
            "candidateNotes": null,
            "clientNotes": null,
            "subscribedUserIds": null,
            "categoryName": null,
            "subCategoryName": null
        },
        {
            "id": "gXbT4JEBZQG_1GkRVAU9",
            "category": "JOBS",
            "subCategory": "CLIENT_MOBILE_NEW_SUBMITTAL",
            "subject": "New Submittal",
            "content": "You have a new submittal for Dialyze Direct-Maryland Certified Medical Assistant - EKG Tech",
            "clientContactId": 2399211,
            "candidateId": 20561591,
            "clientId": 830410,
            "pinToTop": false,
            "favourite": false,
            "organizationId": 149,
            "createdBy": 691421,
            "notificationRead": false,
            "candidateName": "Gary Pm",
            "clientName": "Dialyze Direct-Maryland",
            "entityId": null,
            "createdDate": "09-11-2024 11:23:51",
            "createdDateZoned": "2024-09-11T11:23:51Z",
            "modifiedBy": 691421,
            "modifiedDate": "09-11-2024 11:23:51",
            "professionId": null,
            "professionIds": null,
            "orderId": null,
            "specialtyId": null,
            "specialtyIds": null,
            "jobSubmittalId": 762873,
            "jobId": 14543787,
            "orderCandidateId": null,
            "displayOnExternalJobBoard": true,
            "shiftAccepted": false,
            "shiftDate": null,
            "jobEndDate": "2024-12-21",
            "offerAcceptedDate": null,
            "title": null,
            "candidateNotes": null,
            "clientNotes": null,
            "subscribedUserIds": null,
            "categoryName": null,
            "subCategoryName": null
        },
        {
            "id": "cXbR4JEBZQG_1GkRdQW8",
            "category": "JOBS",
            "subCategory": "CLIENT_MOBILE_NEW_SUBMITTAL",
            "subject": "New Submittal",
            "content": "You have a new submittal for Dialyze Direct-Maryland Certified Medical Assistant - EKG Tech",
            "clientContactId": 2399211,
            "candidateId": 20561591,
            "clientId": 830410,
            "pinToTop": false,
            "favourite": false,
            "organizationId": 149,
            "createdBy": 691421,
            "notificationRead": false,
            "candidateName": "Gary Pm",
            "clientName": "Dialyze Direct-Maryland",
            "entityId": null,
            "createdDate": "09-11-2024 11:21:49",
            "createdDateZoned": "2024-09-11T11:21:49Z",
            "modifiedBy": 691421,
            "modifiedDate": "09-11-2024 11:21:49",
            "professionId": null,
            "professionIds": null,
            "orderId": null,
            "specialtyId": null,
            "specialtyIds": null,
            "jobSubmittalId": 762873,
            "jobId": 14543787,
            "orderCandidateId": null,
            "displayOnExternalJobBoard": true,
            "shiftAccepted": false,
            "shiftDate": null,
            "jobEndDate": "2024-12-21",
            "offerAcceptedDate": null,
            "title": null,
            "candidateNotes": null,
            "clientNotes": null,
            "subscribedUserIds": null,
            "categoryName": null,
            "subCategoryName": null
        },
        {
            "id": "OXa_4JEBZQG_1GkRqQW-",
            "category": "JOBS",
            "subCategory": "CLIENT_MOBILE_NEW_SUBMITTAL",
            "subject": "New Submittal",
            "content": "You have a new submittal for Dialyze Direct-Maryland Certified Medical Assistant - EKG Tech",
            "clientContactId": 2399211,
            "candidateId": 20561591,
            "clientId": 830410,
            "pinToTop": false,
            "favourite": false,
            "organizationId": 149,
            "createdBy": 691421,
            "notificationRead": false,
            "candidateName": "Gary Pm",
            "clientName": "Dialyze Direct-Maryland",
            "entityId": null,
            "createdDate": "09-11-2024 11:02:22",
            "createdDateZoned": "2024-09-11T11:02:22Z",
            "modifiedBy": 691421,
            "modifiedDate": "09-11-2024 11:02:22",
            "professionId": null,
            "professionIds": null,
            "orderId": null,
            "specialtyId": null,
            "specialtyIds": null,
            "jobSubmittalId": 762873,
            "jobId": 14543787,
            "orderCandidateId": null,
            "displayOnExternalJobBoard": true,
            "shiftAccepted": false,
            "shiftDate": null,
            "jobEndDate": "2024-12-21",
            "offerAcceptedDate": null,
            "title": null,
            "candidateNotes": null,
            "clientNotes": null,
            "subscribedUserIds": null,
            "categoryName": null,
            "subCategoryName": null
        },
        {
            "id": "KXa_4JEBZQG_1GkRMQUx",
            "category": "JOBS",
            "subCategory": "CLIENT_MOBILE_NEW_SUBMITTAL",
            "subject": "New Submittal",
            "content": "You have a new submittal for Dialyze Direct-Maryland Certified Medical Assistant - EKG Tech",
            "clientContactId": 2399211,
            "candidateId": 20561591,
            "clientId": 830410,
            "pinToTop": false,
            "favourite": false,
            "organizationId": 149,
            "createdBy": 691421,
            "notificationRead": false,
            "candidateName": "Gary Pm",
            "clientName": "Dialyze Direct-Maryland",
            "entityId": null,
            "createdDate": "09-11-2024 11:01:51",
            "createdDateZoned": "2024-09-11T11:01:51Z",
            "modifiedBy": 691421,
            "modifiedDate": "09-11-2024 11:01:51",
            "professionId": null,
            "professionIds": null,
            "orderId": null,
            "specialtyId": null,
            "specialtyIds": null,
            "jobSubmittalId": 762873,
            "jobId": 14543787,
            "orderCandidateId": null,
            "displayOnExternalJobBoard": true,
            "shiftAccepted": false,
            "shiftDate": null,
            "jobEndDate": "2024-12-21",
            "offerAcceptedDate": null,
            "title": null,
            "candidateNotes": null,
            "clientNotes": null,
            "subscribedUserIds": null,
            "categoryName": null,
            "subCategoryName": null
        },
        {
            "id": "GXa-4JEBZQG_1GkRvQUd",
            "category": "JOBS",
            "subCategory": "CLIENT_MOBILE_NEW_SUBMITTAL",
            "subject": "New Submittal",
            "content": "You have a new submittal for Dialyze Direct-Maryland Certified Medical Assistant - EKG Tech",
            "clientContactId": 2399211,
            "candidateId": 20561591,
            "clientId": 830410,
            "pinToTop": false,
            "favourite": false,
            "organizationId": 149,
            "createdBy": 691421,
            "notificationRead": false,
            "candidateName": "Gary Pm",
            "clientName": "Dialyze Direct-Maryland",
            "entityId": null,
            "createdDate": "09-11-2024 11:01:22",
            "createdDateZoned": "2024-09-11T11:01:22Z",
            "modifiedBy": 691421,
            "modifiedDate": "09-11-2024 11:01:22",
            "professionId": null,
            "professionIds": null,
            "orderId": null,
            "specialtyId": null,
            "specialtyIds": null,
            "jobSubmittalId": 762873,
            "jobId": 14543787,
            "orderCandidateId": null,
            "displayOnExternalJobBoard": true,
            "shiftAccepted": false,
            "shiftDate": null,
            "jobEndDate": "2024-12-21",
            "offerAcceptedDate": null,
            "title": null,
            "candidateNotes": null,
            "clientNotes": null,
            "subscribedUserIds": null,
            "categoryName": null,
            "subCategoryName": null
        },
        {
            "id": "Ana94JEBZQG_1GkRkwUx",
            "category": "JOBS",
            "subCategory": "CLIENT_MOBILE_NEW_SUBMITTAL",
            "subject": "New Submittal",
            "content": "You have a new submittal for Dialyze Direct-Maryland Certified Medical Assistant - EKG Tech",
            "clientContactId": 2399211,
            "candidateId": 20561591,
            "clientId": 830410,
            "pinToTop": false,
            "favourite": false,
            "organizationId": 149,
            "createdBy": 691421,
            "notificationRead": false,
            "candidateName": "Gary Pm",
            "clientName": "Dialyze Direct-Maryland",
            "entityId": null,
            "createdDate": "09-11-2024 11:00:05",
            "createdDateZoned": "2024-09-11T11:00:05Z",
            "modifiedBy": 691421,
            "modifiedDate": "09-11-2024 11:00:05",
            "professionId": null,
            "professionIds": null,
            "orderId": null,
            "specialtyId": null,
            "specialtyIds": null,
            "jobSubmittalId": 762873,
            "jobId": 14543787,
            "orderCandidateId": null,
            "displayOnExternalJobBoard": true,
            "shiftAccepted": false,
            "shiftDate": null,
            "jobEndDate": "2024-12-21",
            "offerAcceptedDate": null,
            "title": null,
            "candidateNotes": null,
            "clientNotes": null,
            "subscribedUserIds": null,
            "categoryName": null,
            "subCategoryName": null
        },
        {
            "id": "rnao4JEBZQG_1GkR7gSa",
            "category": "JOBS",
            "subCategory": "CLIENT_MOBILE_NEW_SUBMITTAL",
            "subject": "New Submittal",
            "content": "You have a new submittal for Dialyze Direct-Maryland Certified Medical Assistant - EKG Tech",
            "clientContactId": 2399211,
            "candidateId": 20561591,
            "clientId": 830410,
            "pinToTop": false,
            "favourite": false,
            "organizationId": 149,
            "createdBy": 691421,
            "notificationRead": false,
            "candidateName": "Gary Pm",
            "clientName": "Dialyze Direct-Maryland",
            "entityId": null,
            "createdDate": "09-11-2024 10:37:33",
            "createdDateZoned": "2024-09-11T10:37:33Z",
            "modifiedBy": 691421,
            "modifiedDate": "09-11-2024 10:37:33",
            "professionId": null,
            "professionIds": null,
            "orderId": null,
            "specialtyId": null,
            "specialtyIds": null,
            "jobSubmittalId": 762873,
            "jobId": 14543787,
            "orderCandidateId": null,
            "displayOnExternalJobBoard": true,
            "shiftAccepted": false,
            "shiftDate": null,
            "jobEndDate": "2024-12-21",
            "offerAcceptedDate": null,
            "title": null,
            "candidateNotes": null,
            "clientNotes": null,
            "subscribedUserIds": null,
            "categoryName": null,
            "subCategoryName": null
        },
        {
            "id": "nXao4JEBZQG_1GkRJgSW",
            "category": "JOBS",
            "subCategory": "CLIENT_MOBILE_NEW_SUBMITTAL",
            "subject": "New Submittal",
            "content": "You have a new submittal for Dialyze Direct-Maryland Certified Medical Assistant - EKG Tech",
            "clientContactId": 2399211,
            "candidateId": 20561591,
            "clientId": 830410,
            "pinToTop": false,
            "favourite": false,
            "organizationId": 149,
            "createdBy": 691421,
            "notificationRead": false,
            "candidateName": "Gary Pm",
            "clientName": "Dialyze Direct-Maryland",
            "entityId": null,
            "createdDate": "09-11-2024 10:36:41",
            "createdDateZoned": "2024-09-11T10:36:41Z",
            "modifiedBy": 691421,
            "modifiedDate": "09-11-2024 10:36:41",
            "professionId": null,
            "professionIds": null,
            "orderId": null,
            "specialtyId": null,
            "specialtyIds": null,
            "jobSubmittalId": 762873,
            "jobId": 14543787,
            "orderCandidateId": null,
            "displayOnExternalJobBoard": true,
            "shiftAccepted": false,
            "shiftDate": null,
            "jobEndDate": "2024-12-21",
            "offerAcceptedDate": null,
            "title": null,
            "candidateNotes": null,
            "clientNotes": null,
            "subscribedUserIds": null,
            "categoryName": null,
            "subCategoryName": null
        },
        {
            "id": "PHaG4JEBZQG_1GkRGQNz",
            "category": "JOBS",
            "subCategory": "CLIENT_MOBILE_NEW_SUBMITTAL",
            "subject": "New Submittal",
            "content": "You have a new submittal for Dialyze Direct-Maryland Certified Medical Assistant - EKG Tech",
            "clientContactId": 2399211,
            "candidateId": 20561591,
            "clientId": 830410,
            "pinToTop": false,
            "favourite": false,
            "organizationId": 149,
            "createdBy": 691421,
            "notificationRead": false,
            "candidateName": "Gary Pm",
            "clientName": "Dialyze Direct-Maryland",
            "entityId": null,
            "createdDate": "09-11-2024 09:59:30",
            "createdDateZoned": "2024-09-11T09:59:30Z",
            "modifiedBy": 691421,
            "modifiedDate": "09-11-2024 09:59:30",
            "professionId": null,
            "professionIds": null,
            "orderId": null,
            "specialtyId": null,
            "specialtyIds": null,
            "jobSubmittalId": 762873,
            "jobId": 14543787,
            "orderCandidateId": null,
            "displayOnExternalJobBoard": true,
            "shiftAccepted": false,
            "shiftDate": null,
            "jobEndDate": "2024-12-21",
            "offerAcceptedDate": null,
            "title": null,
            "candidateNotes": null,
            "clientNotes": null,
            "subscribedUserIds": null,
            "categoryName": null,
            "subCategoryName": null
        }
    ]
}


const subCategoryObject = res.notifications.reduce( ( acc, ele )=> { 
    acc[ele.subCategory] = ele.subCategory

    return acc
}, {});

console.log( JSON.stringify(subCategoryObject, null, 2))