const data = [
    {
        "id": "xXVMmJEBZQG_1GkRjV6R",
        "category": "SCHEDULER",
        "subCategory": "CLIENT_SHIFT_DECLINED_ACCEPTED",
        "subject": "One of your shifts has been cancelled!",
        "content": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE \nGary Pm - CNA\n7am - 5:30pm\n08-30-2024",
        "clientContactId": 2399115,
        "candidateId": 20561591,
        "clientId": 244138,
        "pinToTop": false,
        "favourite": false,
        "organizationId": 149,
        "createdBy": 691451,
        "notificationRead": true,
        "candidateName": "Gary Pm",
        "clientName": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ",
        "entityId": null,
        "createdDate": "08-28-2024 09:23:59",
        "createdDateZoned": "2024-08-28T09:23:59Z",
        "modifiedBy": 691451,
        "modifiedDate": "08-28-2024 09:23:59",
        "professionId": null,
        "professionIds": null,
        "orderId": 223525,
        "specialtyId": null,
        "specialtyIds": null,
        "jobSubmittalId": null,
        "jobId": null,
        "orderCandidateId": null,
        "displayOnExternalJobBoard": null,
        "shiftAccepted": false,
        "shiftDate": "2024-08-30",
        "jobEndDate": null,
        "offerAcceptedDate": null,
        "title": null,
        "candidateNotes": null,
        "clientNotes": null,
        "subscribedUserIds": null,
        "categoryName": null,
        "subCategoryName": null
    },
    {
        "id": "p3VMmJEBZQG_1GkRKl6N",
        "category": "SCHEDULER",
        "subCategory": "CLIENT_CANDIDATE_REQUESTED_SHIFT",
        "subject": "Gary Pm - Requested Shift",
        "content": "Gary Pm has requested to pick up 7am - 7:30pm shift for RN-ER at ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE  on 10-19-2024. Would you like to confirm this candidate?",
        "clientContactId": 2399115,
        "candidateId": 20561591,
        "clientId": 244138,
        "pinToTop": false,
        "favourite": false,
        "organizationId": 149,
        "createdBy": 691422,
        "notificationRead": false,
        "candidateName": "Gary Pm",
        "clientName": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ",
        "entityId": null,
        "createdDate": "08-28-2024 09:23:34",
        "createdDateZoned": "2024-08-28T09:23:34Z",
        "modifiedBy": 691422,
        "modifiedDate": "08-28-2024 09:23:34",
        "professionId": null,
        "professionIds": null,
        "orderId": 223552,
        "specialtyId": null,
        "specialtyIds": null,
        "jobSubmittalId": null,
        "jobId": null,
        "orderCandidateId": null,
        "displayOnExternalJobBoard": null,
        "shiftAccepted": false,
        "shiftDate": "2024-10-19",
        "jobEndDate": null,
        "offerAcceptedDate": null,
        "title": null,
        "candidateNotes": null,
        "clientNotes": null,
        "subscribedUserIds": null,
        "categoryName": null,
        "subCategoryName": null
    },
    {
        "id": "o3VKmJEBZQG_1GkR9V7f",
        "category": "SCHEDULER",
        "subCategory": "CLIENT_SHIFT_DECLINED_ACCEPTED",
        "subject": "One of your shifts has been filled!",
        "content": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE \nGary Pm - RN\n7am - 7:30pm\n10-19-2024",
        "clientContactId": 2399115,
        "candidateId": 20561591,
        "clientId": 244138,
        "pinToTop": false,
        "favourite": false,
        "organizationId": 149,
        "createdBy": 691451,
        "notificationRead": false,
        "candidateName": "Gary Pm",
        "clientName": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ",
        "entityId": null,
        "createdDate": "08-28-2024 09:22:14",
        "createdDateZoned": "2024-08-28T09:22:14Z",
        "modifiedBy": 691451,
        "modifiedDate": "08-28-2024 09:22:14",
        "professionId": null,
        "professionIds": null,
        "orderId": 223552,
        "specialtyId": null,
        "specialtyIds": null,
        "jobSubmittalId": null,
        "jobId": null,
        "orderCandidateId": null,
        "displayOnExternalJobBoard": null,
        "shiftAccepted": true,
        "shiftDate": "2024-10-19",
        "jobEndDate": null,
        "offerAcceptedDate": null,
        "title": null,
        "candidateNotes": null,
        "clientNotes": null,
        "subscribedUserIds": null,
        "categoryName": null,
        "subCategoryName": null
    },
    {
        "id": "fnVJmJEBZQG_1GkRGF7c",
        "category": "SCHEDULER",
        "subCategory": "CLIENT_CANDIDATE_REQUESTED_SHIFT",
        "subject": "Daphne Blake - Requested Shift",
        "content": "Daphne Blake has requested to pick up 7am - 7:30pm shift for RN-ER at ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE  on 10-19-2024. Would you like to confirm this candidate?",
        "clientContactId": 2399115,
        "candidateId": 20561763,
        "clientId": 244138,
        "pinToTop": false,
        "favourite": false,
        "organizationId": 149,
        "createdBy": 691422,
        "notificationRead": false,
        "candidateName": "Daphne Blake",
        "clientName": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ",
        "entityId": null,
        "createdDate": "08-28-2024 09:20:12",
        "createdDateZoned": "2024-08-28T09:20:12Z",
        "modifiedBy": 691422,
        "modifiedDate": "08-28-2024 09:20:12",
        "professionId": null,
        "professionIds": null,
        "orderId": 223552,
        "specialtyId": null,
        "specialtyIds": null,
        "jobSubmittalId": null,
        "jobId": null,
        "orderCandidateId": null,
        "displayOnExternalJobBoard": null,
        "shiftAccepted": false,
        "shiftDate": "2024-10-19",
        "jobEndDate": null,
        "offerAcceptedDate": null,
        "title": null,
        "candidateNotes": null,
        "clientNotes": null,
        "subscribedUserIds": null,
        "categoryName": null,
        "subCategoryName": null
    },
    {
        "id": "RHVCmJEBZQG_1GkRw14v",
        "category": "SCHEDULER",
        "subCategory": "CLIENT_CANDIDATE_REQUESTED_SHIFT",
        "subject": "Ari Vidallo - Requested Shift",
        "content": "Ari Vidallo has requested to pick up 7am - 7:30pm shift for RN-ER at ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE  on 10-18-2024. Would you like to confirm this candidate?",
        "clientContactId": 2399115,
        "candidateId": 14465768,
        "clientId": 244138,
        "pinToTop": false,
        "favourite": false,
        "organizationId": 149,
        "createdBy": 691422,
        "notificationRead": false,
        "candidateName": "Ari Vidallo",
        "clientName": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ",
        "entityId": null,
        "createdDate": "08-28-2024 09:13:17",
        "createdDateZoned": "2024-08-28T09:13:17Z",
        "modifiedBy": 691422,
        "modifiedDate": "08-28-2024 09:13:17",
        "professionId": null,
        "professionIds": null,
        "orderId": 223551,
        "specialtyId": null,
        "specialtyIds": null,
        "jobSubmittalId": null,
        "jobId": null,
        "orderCandidateId": null,
        "displayOnExternalJobBoard": null,
        "shiftAccepted": false,
        "shiftDate": "2024-10-18",
        "jobEndDate": null,
        "offerAcceptedDate": null,
        "title": null,
        "candidateNotes": null,
        "clientNotes": null,
        "subscribedUserIds": null,
        "categoryName": null,
        "subCategoryName": null
    },
    {
        "id": "G3VBmJEBZQG_1GkRKl7b",
        "category": "SCHEDULER",
        "subCategory": "CLIENT_CANDIDATE_REQUESTED_SHIFT",
        "subject": "Vinay Test Test - Requested Shift",
        "content": "Vinay Test Test has requested to pick up 7am - 7:30pm shift for RN-ER at ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE  on 10-18-2024. Would you like to confirm this candidate?",
        "clientContactId": 2399115,
        "candidateId": 20561883,
        "clientId": 244138,
        "pinToTop": false,
        "favourite": false,
        "organizationId": 149,
        "createdBy": 691422,
        "notificationRead": false,
        "candidateName": "Vinay Test Test",
        "clientName": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ",
        "entityId": null,
        "createdDate": "08-28-2024 09:11:33",
        "createdDateZoned": "2024-08-28T09:11:33Z",
        "modifiedBy": 691422,
        "modifiedDate": "08-28-2024 09:11:33",
        "professionId": null,
        "professionIds": null,
        "orderId": 223551,
        "specialtyId": null,
        "specialtyIds": null,
        "jobSubmittalId": null,
        "jobId": null,
        "orderCandidateId": null,
        "displayOnExternalJobBoard": null,
        "shiftAccepted": false,
        "shiftDate": "2024-10-18",
        "jobEndDate": null,
        "offerAcceptedDate": null,
        "title": null,
        "candidateNotes": null,
        "clientNotes": null,
        "subscribedUserIds": null,
        "categoryName": null,
        "subCategoryName": null
    },
    {
        "id": "2XU4mJEBZQG_1GkRK10L",
        "category": "SCHEDULER",
        "subCategory": "CLIENT_CANDIDATE_REQUESTED_SHIFT",
        "subject": "Bill Gates - Requested Shift",
        "content": "Bill Gates has requested to pick up 7am - 5:30pm shift for RN-ER at ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE  on 08-10-2024. Would you like to confirm this candidate?",
        "clientContactId": 2399115,
        "candidateId": 20561730,
        "clientId": 244138,
        "pinToTop": false,
        "favourite": false,
        "organizationId": 149,
        "createdBy": 691422,
        "notificationRead": true,
        "candidateName": "Bill Gates",
        "clientName": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ",
        "entityId": null,
        "createdDate": "08-28-2024 09:01:43",
        "createdDateZoned": "2024-08-28T09:01:43Z",
        "modifiedBy": 691422,
        "modifiedDate": "08-28-2024 09:01:43",
        "professionId": null,
        "professionIds": null,
        "orderId": 223550,
        "specialtyId": null,
        "specialtyIds": null,
        "jobSubmittalId": null,
        "jobId": null,
        "orderCandidateId": null,
        "displayOnExternalJobBoard": null,
        "shiftAccepted": false,
        "shiftDate": "2024-08-10",
        "jobEndDate": null,
        "offerAcceptedDate": null,
        "title": null,
        "candidateNotes": null,
        "clientNotes": null,
        "subscribedUserIds": null,
        "categoryName": null,
        "subCategoryName": null
    },
    {
        "id": "f3UwmJEBZQG_1GkRn11N",
        "category": "SCHEDULER",
        "subCategory": "CLIENT_CANDIDATE_REQUESTED_SHIFT",
        "subject": "Gary Pm - Requested Shift",
        "content": "Gary Pm has requested to pick up 7am - 5:30pm shift for RN-ER at ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE  on 08-10-2024. Would you like to confirm this candidate?",
        "clientContactId": 2399115,
        "candidateId": 20561591,
        "clientId": 244138,
        "pinToTop": false,
        "favourite": false,
        "organizationId": 149,
        "createdBy": 691451,
        "notificationRead": false,
        "candidateName": "Gary Pm",
        "clientName": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ",
        "entityId": null,
        "createdDate": "08-28-2024 08:53:28",
        "createdDateZoned": "2024-08-28T08:53:28Z",
        "modifiedBy": 691451,
        "modifiedDate": "08-28-2024 08:53:28",
        "professionId": null,
        "professionIds": null,
        "orderId": 222598,
        "specialtyId": null,
        "specialtyIds": null,
        "jobSubmittalId": null,
        "jobId": null,
        "orderCandidateId": null,
        "displayOnExternalJobBoard": null,
        "shiftAccepted": false,
        "shiftDate": "2024-08-10",
        "jobEndDate": null,
        "offerAcceptedDate": null,
        "title": null,
        "candidateNotes": null,
        "clientNotes": null,
        "subscribedUserIds": null,
        "categoryName": null,
        "subCategoryName": null
    },
    {
        "id": "bXUumJEBZQG_1GkRDF1z",
        "category": "SCHEDULER",
        "subCategory": "CLIENT_CANDIDATE_REQUESTED_SHIFT",
        "subject": "Ari Vidallo - Requested Shift",
        "content": "Ari Vidallo has requested to pick up 7am - 7:30pm shift for RN-ER at ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE  on 10-17-2024. Would you like to confirm this candidate?",
        "clientContactId": 2399115,
        "candidateId": 14465768,
        "clientId": 244138,
        "pinToTop": false,
        "favourite": false,
        "organizationId": 149,
        "createdBy": 691422,
        "notificationRead": false,
        "candidateName": "Ari Vidallo",
        "clientName": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ",
        "entityId": null,
        "createdDate": "08-28-2024 08:50:40",
        "createdDateZoned": "2024-08-28T08:50:40Z",
        "modifiedBy": 691422,
        "modifiedDate": "08-28-2024 08:50:40",
        "professionId": null,
        "professionIds": null,
        "orderId": 223549,
        "specialtyId": null,
        "specialtyIds": null,
        "jobSubmittalId": null,
        "jobId": null,
        "orderCandidateId": null,
        "displayOnExternalJobBoard": null,
        "shiftAccepted": false,
        "shiftDate": "2024-10-17",
        "jobEndDate": null,
        "offerAcceptedDate": null,
        "title": null,
        "candidateNotes": null,
        "clientNotes": null,
        "subscribedUserIds": null,
        "categoryName": null,
        "subCategoryName": null
    },
    {
        "id": "c3Xnl5EBZQG_1GkRqFwc",
        "category": "SCHEDULER",
        "subCategory": "CLIENT_SHIFT_DECLINED_ACCEPTED",
        "subject": "One of your shifts has been filled!",
        "content": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE \nJim Pm - RN\n7am - 7:30pm\n08-31-2024",
        "clientContactId": 2399115,
        "candidateId": 20562352,
        "clientId": 244138,
        "pinToTop": false,
        "favourite": false,
        "organizationId": 149,
        "createdBy": 692266,
        "notificationRead": false,
        "candidateName": "Jim Pm",
        "clientName": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ",
        "entityId": null,
        "createdDate": "08-28-2024 07:33:47",
        "createdDateZoned": "2024-08-28T07:33:47Z",
        "modifiedBy": 692266,
        "modifiedDate": "08-28-2024 07:33:47",
        "professionId": null,
        "professionIds": null,
        "orderId": 223203,
        "specialtyId": null,
        "specialtyIds": null,
        "jobSubmittalId": null,
        "jobId": null,
        "orderCandidateId": null,
        "displayOnExternalJobBoard": null,
        "shiftAccepted": true,
        "shiftDate": "2024-08-31",
        "jobEndDate": null,
        "offerAcceptedDate": null,
        "title": null,
        "candidateNotes": null,
        "clientNotes": null,
        "subscribedUserIds": null,
        "categoryName": null,
        "subCategoryName": null
    },
    {
        "id": "U3Xgl5EBZQG_1GkRYVyi",
        "category": "SCHEDULER",
        "subCategory": "CLIENT_NOTIFIED_PRN_SHIFT_CANCELLED",
        "subject": "Gary Pm - Cancelled Shift",
        "content": "Gary Pm has canceled their 7am - 5:30pm at ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE  on 09-04-2024. Do you want to backfill this shift?",
        "clientContactId": 2399115,
        "candidateId": 20561591,
        "clientId": 244138,
        "pinToTop": false,
        "favourite": false,
        "organizationId": 149,
        "createdBy": 691451,
        "notificationRead": true,
        "candidateName": "Gary Pm",
        "clientName": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ",
        "entityId": null,
        "createdDate": "08-28-2024 07:25:50",
        "createdDateZoned": "2024-08-28T07:25:50Z",
        "modifiedBy": 691451,
        "modifiedDate": "08-28-2024 07:25:50",
        "professionId": null,
        "professionIds": null,
        "orderId": 222972,
        "specialtyId": null,
        "specialtyIds": null,
        "jobSubmittalId": null,
        "jobId": null,
        "orderCandidateId": null,
        "displayOnExternalJobBoard": null,
        "shiftAccepted": false,
        "shiftDate": "2024-09-04",
        "jobEndDate": null,
        "offerAcceptedDate": null,
        "title": null,
        "candidateNotes": null,
        "clientNotes": null,
        "subscribedUserIds": null,
        "categoryName": null,
        "subCategoryName": null
    },
    {
        "id": "Q3Xdl5EBZQG_1GkRsly5",
        "category": "SCHEDULER",
        "subCategory": "CLIENT_CANDIDATE_REQUESTED_SHIFT",
        "subject": "Gary Pm - Requested Shift",
        "content": "Gary Pm has requested to pick up 7am - 5:30pm shift for CNA-Acute at ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE  on 09-04-2024. Would you like to confirm this candidate?",
        "clientContactId": 2399115,
        "candidateId": 20561591,
        "clientId": 244138,
        "pinToTop": false,
        "favourite": false,
        "organizationId": 149,
        "createdBy": 691421,
        "notificationRead": true,
        "candidateName": "Gary Pm",
        "clientName": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ",
        "entityId": null,
        "createdDate": "08-28-2024 07:22:54",
        "createdDateZoned": "2024-08-28T07:22:54Z",
        "modifiedBy": 691421,
        "modifiedDate": "08-28-2024 07:22:54",
        "professionId": null,
        "professionIds": null,
        "orderId": 222972,
        "specialtyId": null,
        "specialtyIds": null,
        "jobSubmittalId": null,
        "jobId": null,
        "orderCandidateId": null,
        "displayOnExternalJobBoard": null,
        "shiftAccepted": false,
        "shiftDate": "2024-09-04",
        "jobEndDate": null,
        "offerAcceptedDate": null,
        "title": null,
        "candidateNotes": null,
        "clientNotes": null,
        "subscribedUserIds": null,
        "categoryName": null,
        "subCategoryName": null
    },
    {
        "id": "JHXUl5EBZQG_1GkRhVx8",
        "category": "SCHEDULER",
        "subCategory": "CLIENT_SHIFT_DECLINED_ACCEPTED",
        "subject": "One of your shifts has been cancelled!",
        "content": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE \nGary Pm - RN\n7am - 7:30pm\n08-31-2024",
        "clientContactId": 2399115,
        "candidateId": 20561591,
        "clientId": 244138,
        "pinToTop": false,
        "favourite": false,
        "organizationId": 149,
        "createdBy": 691451,
        "notificationRead": true,
        "candidateName": "Gary Pm",
        "clientName": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ",
        "entityId": null,
        "createdDate": "08-28-2024 07:12:52",
        "createdDateZoned": "2024-08-28T07:12:52Z",
        "modifiedBy": 691451,
        "modifiedDate": "08-28-2024 07:12:52",
        "professionId": null,
        "professionIds": null,
        "orderId": 223203,
        "specialtyId": null,
        "specialtyIds": null,
        "jobSubmittalId": null,
        "jobId": null,
        "orderCandidateId": null,
        "displayOnExternalJobBoard": null,
        "shiftAccepted": false,
        "shiftDate": "2024-08-31",
        "jobEndDate": null,
        "offerAcceptedDate": null,
        "title": null,
        "candidateNotes": null,
        "clientNotes": null,
        "subscribedUserIds": null,
        "categoryName": null,
        "subCategoryName": null
    },
    {
        "id": "-XXQl5EBZQG_1GkRmluh",
        "category": "SCHEDULER",
        "subCategory": "CLIENT_CANDIDATE_REQUESTED_SHIFT",
        "subject": "Gary Pm - Requested Shift",
        "content": "Gary Pm has requested to pick up 7am - 5:30pm shift for CNA-Acute at ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE  on 08-30-2024. Would you like to confirm this candidate?",
        "clientContactId": 2399115,
        "candidateId": 20561591,
        "clientId": 244138,
        "pinToTop": false,
        "favourite": false,
        "organizationId": 149,
        "createdBy": 691421,
        "notificationRead": true,
        "candidateName": "Gary Pm",
        "clientName": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ",
        "entityId": null,
        "createdDate": "08-28-2024 07:08:36",
        "createdDateZoned": "2024-08-28T07:08:36Z",
        "modifiedBy": 691421,
        "modifiedDate": "08-28-2024 07:08:36",
        "professionId": null,
        "professionIds": null,
        "orderId": 223524,
        "specialtyId": null,
        "specialtyIds": null,
        "jobSubmittalId": null,
        "jobId": null,
        "orderCandidateId": null,
        "displayOnExternalJobBoard": null,
        "shiftAccepted": false,
        "shiftDate": "2024-08-30",
        "jobEndDate": null,
        "offerAcceptedDate": null,
        "title": null,
        "candidateNotes": null,
        "clientNotes": null,
        "subscribedUserIds": null,
        "categoryName": null,
        "subCategoryName": null
    },
    {
        "id": "4nXOl5EBZQG_1GkRwlty",
        "category": "SCHEDULER",
        "subCategory": "CLIENT_SHIFT_DECLINED_ACCEPTED",
        "subject": "One of your shifts has been cancelled!",
        "content": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE \nGary Pm - CNA\n7am - 5:30pm\n08-30-2024",
        "clientContactId": 2399115,
        "candidateId": 20561591,
        "clientId": 244138,
        "pinToTop": false,
        "favourite": false,
        "organizationId": 149,
        "createdBy": 691451,
        "notificationRead": false,
        "candidateName": "Gary Pm",
        "clientName": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ",
        "entityId": null,
        "createdDate": "08-28-2024 07:06:35",
        "createdDateZoned": "2024-08-28T07:06:35Z",
        "modifiedBy": 691451,
        "modifiedDate": "08-28-2024 07:06:35",
        "professionId": null,
        "professionIds": null,
        "orderId": 223524,
        "specialtyId": null,
        "specialtyIds": null,
        "jobSubmittalId": null,
        "jobId": null,
        "orderCandidateId": null,
        "displayOnExternalJobBoard": null,
        "shiftAccepted": false,
        "shiftDate": "2024-08-30",
        "jobEndDate": null,
        "offerAcceptedDate": null,
        "title": null,
        "candidateNotes": null,
        "clientNotes": null,
        "subscribedUserIds": null,
        "categoryName": null,
        "subCategoryName": null
    },
    {
        "id": "0HXOl5EBZQG_1GkRCFuG",
        "category": "SCHEDULER",
        "subCategory": "CLIENT_CANDIDATE_REQUESTED_SHIFT",
        "subject": "Gary Pm - Requested Shift",
        "content": "Gary Pm has requested to pick up 7am - 5:30pm shift for CNA-Acute at ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE  on 08-30-2024. Would you like to confirm this candidate?",
        "clientContactId": 2399115,
        "candidateId": 20561591,
        "clientId": 244138,
        "pinToTop": false,
        "favourite": false,
        "organizationId": 149,
        "createdBy": 691421,
        "notificationRead": false,
        "candidateName": "Gary Pm",
        "clientName": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ",
        "entityId": null,
        "createdDate": "08-28-2024 07:05:47",
        "createdDateZoned": "2024-08-28T07:05:47Z",
        "modifiedBy": 691421,
        "modifiedDate": "08-28-2024 07:05:47",
        "professionId": null,
        "professionIds": null,
        "orderId": 223524,
        "specialtyId": null,
        "specialtyIds": null,
        "jobSubmittalId": null,
        "jobId": null,
        "orderCandidateId": null,
        "displayOnExternalJobBoard": null,
        "shiftAccepted": false,
        "shiftDate": "2024-08-30",
        "jobEndDate": null,
        "offerAcceptedDate": null,
        "title": null,
        "candidateNotes": null,
        "clientNotes": null,
        "subscribedUserIds": null,
        "categoryName": null,
        "subCategoryName": null
    },
    {
        "id": "v3XNl5EBZQG_1GkRCltH",
        "category": "SCHEDULER",
        "subCategory": "CLIENT_SHIFT_DECLINED_ACCEPTED",
        "subject": "One of your shifts has been cancelled!",
        "content": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE \nGary Pm - CNA\n7am - 5:30pm\n09-04-2024",
        "clientContactId": 2399115,
        "candidateId": 20561591,
        "clientId": 244138,
        "pinToTop": false,
        "favourite": false,
        "organizationId": 149,
        "createdBy": 691451,
        "notificationRead": false,
        "candidateName": "Gary Pm",
        "clientName": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ",
        "entityId": null,
        "createdDate": "08-28-2024 07:04:42",
        "createdDateZoned": "2024-08-28T07:04:42Z",
        "modifiedBy": 691451,
        "modifiedDate": "08-28-2024 07:04:42",
        "professionId": null,
        "professionIds": null,
        "orderId": 223259,
        "specialtyId": null,
        "specialtyIds": null,
        "jobSubmittalId": null,
        "jobId": null,
        "orderCandidateId": null,
        "displayOnExternalJobBoard": null,
        "shiftAccepted": false,
        "shiftDate": "2024-09-04",
        "jobEndDate": null,
        "offerAcceptedDate": null,
        "title": null,
        "candidateNotes": null,
        "clientNotes": null,
        "subscribedUserIds": null,
        "categoryName": null,
        "subCategoryName": null
    },
    {
        "id": "m3XHl5EBZQG_1GkRS1sq",
        "category": "SCHEDULER",
        "subCategory": "CLIENT_CANDIDATE_REQUESTED_SHIFT",
        "subject": "Gary Pm - Requested Shift",
        "content": "Gary Pm has requested to pick up 7am - 5:30pm shift for CNA-Acute at ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE  on 09-04-2024. Would you like to confirm this candidate?",
        "clientContactId": 2399115,
        "candidateId": 20561591,
        "clientId": 244138,
        "pinToTop": false,
        "favourite": false,
        "organizationId": 149,
        "createdBy": 691421,
        "notificationRead": false,
        "candidateName": "Gary Pm",
        "clientName": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ",
        "entityId": null,
        "createdDate": "08-28-2024 06:58:26",
        "createdDateZoned": "2024-08-28T06:58:26Z",
        "modifiedBy": 691421,
        "modifiedDate": "08-28-2024 06:58:26",
        "professionId": null,
        "professionIds": null,
        "orderId": 223259,
        "specialtyId": null,
        "specialtyIds": null,
        "jobSubmittalId": null,
        "jobId": null,
        "orderCandidateId": null,
        "displayOnExternalJobBoard": null,
        "shiftAccepted": false,
        "shiftDate": "2024-09-04",
        "jobEndDate": null,
        "offerAcceptedDate": null,
        "title": null,
        "candidateNotes": null,
        "clientNotes": null,
        "subscribedUserIds": null,
        "categoryName": null,
        "subCategoryName": null
    },
    {
        "id": "gXWzl5EBZQG_1GkRHltj",
        "category": "SCHEDULER",
        "subCategory": "CLIENT_SHIFT_DECLINED_ACCEPTED",
        "subject": "One of your shifts has been cancelled!",
        "content": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE \nGary Pm - CNA\n7am - 5:30pm\n09-09-2024",
        "clientContactId": 2399115,
        "candidateId": 20561591,
        "clientId": 244138,
        "pinToTop": false,
        "favourite": false,
        "organizationId": 149,
        "createdBy": 691451,
        "notificationRead": true,
        "candidateName": "Gary Pm",
        "clientName": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ",
        "entityId": null,
        "createdDate": "08-28-2024 06:36:23",
        "createdDateZoned": "2024-08-28T06:36:23Z",
        "modifiedBy": 691451,
        "modifiedDate": "08-28-2024 06:36:23",
        "professionId": null,
        "professionIds": null,
        "orderId": 223147,
        "specialtyId": null,
        "specialtyIds": null,
        "jobSubmittalId": null,
        "jobId": null,
        "orderCandidateId": null,
        "displayOnExternalJobBoard": null,
        "shiftAccepted": false,
        "shiftDate": "2024-09-09",
        "jobEndDate": null,
        "offerAcceptedDate": null,
        "title": null,
        "candidateNotes": null,
        "clientNotes": null,
        "subscribedUserIds": null,
        "categoryName": null,
        "subCategoryName": null
    },
    {
        "id": "cXWyl5EBZQG_1GkRtFva",
        "category": "SCHEDULER",
        "subCategory": "CLIENT_CANDIDATE_REQUESTED_SHIFT",
        "subject": "Gary Pm - Requested Shift",
        "content": "Gary Pm has requested to pick up 7am - 5:30pm shift for CNA-Acute at ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE  on 09-09-2024. Would you like to confirm this candidate?",
        "clientContactId": 2399115,
        "candidateId": 20561591,
        "clientId": 244138,
        "pinToTop": false,
        "favourite": false,
        "organizationId": 149,
        "createdBy": 691421,
        "notificationRead": false,
        "candidateName": "Gary Pm",
        "clientName": "ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ABBOTT HOUSE ",
        "entityId": null,
        "createdDate": "08-28-2024 06:35:56",
        "createdDateZoned": "2024-08-28T06:35:56Z",
        "modifiedBy": 691421,
        "modifiedDate": "08-28-2024 06:35:56",
        "professionId": null,
        "professionIds": null,
        "orderId": 223147,
        "specialtyId": null,
        "specialtyIds": null,
        "jobSubmittalId": null,
        "jobId": null,
        "orderCandidateId": null,
        "displayOnExternalJobBoard": null,
        "shiftAccepted": false,
        "shiftDate": "2024-09-09",
        "jobEndDate": null,
        "offerAcceptedDate": null,
        "title": null,
        "candidateNotes": null,
        "clientNotes": null,
        "subscribedUserIds": null,
        "categoryName": null,
        "subCategoryName": null
    }
]

function getSubjects(subCategory) {
    console.log("\n" + subCategory)
    data.forEach(ele => {
        if (ele.subCategory == subCategory) {
            console.log(ele.subject)
        }
    })
}

getSubjects('CLIENT_SHIFT_DECLINED_ACCEPTED');
getSubjects('CLIENT_CANDIDATE_REQUESTED_SHIFT');
getSubjects('CLIENT_NOTIFIED_PRN_SHIFT_CANCELLED');